/*
 * This file is generated by jOOQ.
*/
package aug.common.gateway.db.jooq;


import aug.common.gateway.db.jooq.tables.GwRateLimit;
import aug.common.gateway.db.jooq.tables.GwService;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AugGateway extends SchemaImpl {

    private static final long serialVersionUID = -1908691368;

    /**
     * The reference instance of <code>aug_gateway</code>
     */
    public static final AugGateway AUG_GATEWAY = new AugGateway();

    /**
     * 限流配置表
     */
    public final GwRateLimit GW_RATE_LIMIT = aug.common.gateway.db.jooq.tables.GwRateLimit.GW_RATE_LIMIT;

    /**
     * 服务配置表
     */
    public final GwService GW_SERVICE = aug.common.gateway.db.jooq.tables.GwService.GW_SERVICE;

    /**
     * No further instances allowed
     */
    private AugGateway() {
        super("aug_gateway", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            GwRateLimit.GW_RATE_LIMIT,
            GwService.GW_SERVICE);
    }
}
