/*
 * This file is generated by jOOQ.
*/
package aug.common.gateway.db.jooq;


import aug.common.gateway.db.jooq.tables.GwRateLimit;
import aug.common.gateway.db.jooq.tables.GwService;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>aug_gateway</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GW_RATE_LIMIT_PRIMARY = Indexes0.GW_RATE_LIMIT_PRIMARY;
    public static final Index GW_SERVICE_PRIMARY = Indexes0.GW_SERVICE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index GW_RATE_LIMIT_PRIMARY = Internal.createIndex("PRIMARY", GwRateLimit.GW_RATE_LIMIT, new OrderField[] { GwRateLimit.GW_RATE_LIMIT.ID }, true);
        public static Index GW_SERVICE_PRIMARY = Internal.createIndex("PRIMARY", GwService.GW_SERVICE, new OrderField[] { GwService.GW_SERVICE.ID }, true);
    }
}
