/*
 * This file is generated by jOOQ.
*/
package aug.common.gateway.db.jooq;


import aug.common.gateway.db.jooq.tables.GwRateLimit;
import aug.common.gateway.db.jooq.tables.GwService;
import aug.common.gateway.db.jooq.tables.records.GwRateLimitRecord;
import aug.common.gateway.db.jooq.tables.records.GwServiceRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>aug_gateway</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<GwRateLimitRecord, Integer> IDENTITY_GW_RATE_LIMIT = Identities0.IDENTITY_GW_RATE_LIMIT;
    public static final Identity<GwServiceRecord, Integer> IDENTITY_GW_SERVICE = Identities0.IDENTITY_GW_SERVICE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GwRateLimitRecord> KEY_GW_RATE_LIMIT_PRIMARY = UniqueKeys0.KEY_GW_RATE_LIMIT_PRIMARY;
    public static final UniqueKey<GwServiceRecord> KEY_GW_SERVICE_PRIMARY = UniqueKeys0.KEY_GW_SERVICE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<GwRateLimitRecord, Integer> IDENTITY_GW_RATE_LIMIT = Internal.createIdentity(GwRateLimit.GW_RATE_LIMIT, GwRateLimit.GW_RATE_LIMIT.ID);
        public static Identity<GwServiceRecord, Integer> IDENTITY_GW_SERVICE = Internal.createIdentity(GwService.GW_SERVICE, GwService.GW_SERVICE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<GwRateLimitRecord> KEY_GW_RATE_LIMIT_PRIMARY = Internal.createUniqueKey(GwRateLimit.GW_RATE_LIMIT, "KEY_gw_rate_limit_PRIMARY", GwRateLimit.GW_RATE_LIMIT.ID);
        public static final UniqueKey<GwServiceRecord> KEY_GW_SERVICE_PRIMARY = Internal.createUniqueKey(GwService.GW_SERVICE, "KEY_gw_service_PRIMARY", GwService.GW_SERVICE.ID);
    }
}
