/*
 * This file is generated by jOOQ.
*/
package aug.common.gateway.db.jooq.tables.records;


import aug.common.gateway.db.jooq.tables.GwService;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 服务配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GwServiceRecord extends UpdatableRecordImpl<GwServiceRecord> implements Record9<Integer, String, Integer, String, String, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -814680533;

    /**
     * Setter for <code>aug_gateway.gw_service.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>aug_gateway.gw_service.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>aug_gateway.gw_service.service_code</code>.
     */
    public void setServiceCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>aug_gateway.gw_service.service_code</code>.
     */
    public String getServiceCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>aug_gateway.gw_service.service_num</code>.
     */
    public void setServiceNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>aug_gateway.gw_service.service_num</code>.
     */
    public Integer getServiceNum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>aug_gateway.gw_service.service_name</code>.
     */
    public void setServiceName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>aug_gateway.gw_service.service_name</code>.
     */
    public String getServiceName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>aug_gateway.gw_service.host</code>.
     */
    public void setHost(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>aug_gateway.gw_service.host</code>.
     */
    public String getHost() {
        return (String) get(4);
    }

    /**
     * Setter for <code>aug_gateway.gw_service.port</code>.
     */
    public void setPort(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>aug_gateway.gw_service.port</code>.
     */
    public Integer getPort() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>aug_gateway.gw_service.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>aug_gateway.gw_service.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>aug_gateway.gw_service.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>aug_gateway.gw_service.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>aug_gateway.gw_service.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>aug_gateway.gw_service.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, String, String, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, String, String, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GwService.GW_SERVICE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GwService.GW_SERVICE.SERVICE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GwService.GW_SERVICE.SERVICE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GwService.GW_SERVICE.SERVICE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return GwService.GW_SERVICE.HOST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return GwService.GW_SERVICE.PORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return GwService.GW_SERVICE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return GwService.GW_SERVICE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return GwService.GW_SERVICE.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getServiceCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getServiceNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getServiceCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getServiceNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord value2(String value) {
        setServiceCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord value3(Integer value) {
        setServiceNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord value4(String value) {
        setServiceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord value5(String value) {
        setHost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord value6(Integer value) {
        setPort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord value9(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwServiceRecord values(Integer value1, String value2, Integer value3, String value4, String value5, Integer value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GwServiceRecord
     */
    public GwServiceRecord() {
        super(GwService.GW_SERVICE);
    }

    /**
     * Create a detached, initialised GwServiceRecord
     */
    public GwServiceRecord(Integer id, String serviceCode, Integer serviceNum, String serviceName, String host, Integer port, String status, Timestamp createdAt, Timestamp updatedAt) {
        super(GwService.GW_SERVICE);

        set(0, id);
        set(1, serviceCode);
        set(2, serviceNum);
        set(3, serviceName);
        set(4, host);
        set(5, port);
        set(6, status);
        set(7, createdAt);
        set(8, updatedAt);
    }
}
