/*
 * This file is generated by jOOQ.
*/
package aug.common.gateway.db.jooq.tables;


import aug.common.gateway.db.jooq.AugGateway;
import aug.common.gateway.db.jooq.Indexes;
import aug.common.gateway.db.jooq.Keys;
import aug.common.gateway.db.jooq.tables.records.GwRateLimitRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 限流配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GwRateLimit extends TableImpl<GwRateLimitRecord> {

    private static final long serialVersionUID = -1214467657;

    /**
     * The reference instance of <code>aug_gateway.gw_rate_limit</code>
     */
    public static final GwRateLimit GW_RATE_LIMIT = new GwRateLimit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GwRateLimitRecord> getRecordType() {
        return GwRateLimitRecord.class;
    }

    /**
     * The column <code>aug_gateway.gw_rate_limit.id</code>.
     */
    public final TableField<GwRateLimitRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>aug_gateway.gw_rate_limit.service_code</code>.
     */
    public final TableField<GwRateLimitRecord, String> SERVICE_CODE = createField("service_code", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>aug_gateway.gw_rate_limit.limit_type</code>.
     */
    public final TableField<GwRateLimitRecord, String> LIMIT_TYPE = createField("limit_type", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>aug_gateway.gw_rate_limit.limit_count</code>.
     */
    public final TableField<GwRateLimitRecord, Long> LIMIT_COUNT = createField("limit_count", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>aug_gateway.gw_rate_limit.interval</code>.
     */
    public final TableField<GwRateLimitRecord, Long> INTERVAL = createField("interval", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>aug_gateway.gw_rate_limit.time_unit</code>.
     */
    public final TableField<GwRateLimitRecord, String> TIME_UNIT = createField("time_unit", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>aug_gateway.gw_rate_limit.created_at</code>.
     */
    public final TableField<GwRateLimitRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>aug_gateway.gw_rate_limit.updated_at</code>.
     */
    public final TableField<GwRateLimitRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>aug_gateway.gw_rate_limit</code> table reference
     */
    public GwRateLimit() {
        this(DSL.name("gw_rate_limit"), null);
    }

    /**
     * Create an aliased <code>aug_gateway.gw_rate_limit</code> table reference
     */
    public GwRateLimit(String alias) {
        this(DSL.name(alias), GW_RATE_LIMIT);
    }

    /**
     * Create an aliased <code>aug_gateway.gw_rate_limit</code> table reference
     */
    public GwRateLimit(Name alias) {
        this(alias, GW_RATE_LIMIT);
    }

    private GwRateLimit(Name alias, Table<GwRateLimitRecord> aliased) {
        this(alias, aliased, null);
    }

    private GwRateLimit(Name alias, Table<GwRateLimitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "限流配置表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return AugGateway.AUG_GATEWAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GW_RATE_LIMIT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GwRateLimitRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GW_RATE_LIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GwRateLimitRecord> getPrimaryKey() {
        return Keys.KEY_GW_RATE_LIMIT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GwRateLimitRecord>> getKeys() {
        return Arrays.<UniqueKey<GwRateLimitRecord>>asList(Keys.KEY_GW_RATE_LIMIT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwRateLimit as(String alias) {
        return new GwRateLimit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GwRateLimit as(Name alias) {
        return new GwRateLimit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GwRateLimit rename(String name) {
        return new GwRateLimit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GwRateLimit rename(Name name) {
        return new GwRateLimit(name, null);
    }
}
